// ---------------------------------------------------------------------------
// PROJECT DATA — this is the single file you edit to manage your site's content.
//
// HOW IT WORKS:
//   • `featured: true`  → shows as a big card on the homepage (keep this to 3–6).
//   • everything else    → shows only in the /archive grid.
//   • add a `caseStudy`  → generates a full /projects/<slug> page for that project.
//
// TODO for Joel — search for "TODO" and fill in:
//   • real live/store/GitHub links
//   • screenshots (drop images in /public/projects/ and set `image`)
//   • real results/metrics where you have them
// ---------------------------------------------------------------------------

export type ProjectType = "App" | "AI / Agent" | "Tool" | "Bot" | "Web";
export type ProjectStatus = "shipped" | "wip" | "experiment";

export type Project = {
  slug: string;
  title: string;
  /** One line: what it is + who it's for. Shown everywhere. */
  tagline: string;
  type: ProjectType;
  year: number;
  tech: string[];
  featured?: boolean;
  status?: ProjectStatus;
  /** Optional client-work flag — renders a small "Client work" chip. */
  client?: boolean;
  /** Hero/thumbnail image, e.g. "/projects/onemind.png". Optional. */
  image?: string;
  links?: {
    live?: string;
    github?: string;
    appStore?: string;
    playStore?: string;
  };
  /** Add this to generate a full case-study page at /projects/<slug>. */
  caseStudy?: {
    problem: string;
    build: string[];
    results?: string;
  };
};

export const projects: Project[] = [
  // ======================= FEATURED (homepage) =======================
  {
    slug: "onemind",
    title: "OneMind",
    tagline:
      "A collective-consensus platform where humans and AI agents reach shared decisions.",
    type: "App",
    year: 2026,
    tech: ["Flutter", "Dart", "Supabase", "Edge Functions", "Postgres"],
    featured: true,
    status: "shipped",
    // image: "/projects/onemind.png", // TODO: add screenshot, then uncomment
    links: {
      live: "https://ourmind.life", // TODO: confirm canonical URL
      github: "https://github.com/OneMindLife/OneMind.Life",
    },
    caseStudy: {
      problem:
        "Group decision-making online is noisy and dominated by the loudest voices. I wanted a structured way for a group — including AI agents — to converge on a shared position rather than just argue.",
      build: [
        "Cross-platform app in Flutter with a Supabase (Postgres) backend.",
        "A consensus engine: chats → cycles → iterations → propositions, with a 0–100 rating grid and a 2-in-a-row winner rule.",
        "Multilingual support via per-field, per-language translations generated by an LLM.",
        "Realtime collaboration and vault-based scheduled jobs for background processing.",
      ],
      results:
        "Live at ourmind.life and open-sourced as OneMind.Life.",
    },
  },
  {
    slug: "llm-group-chat",
    title: "LLMGroupChat",
    tagline:
      "A consensus engine where multiple LLMs debate and vote to pick stocks.",
    type: "AI / Agent",
    year: 2026,
    tech: ["Dart", "Supabase", "Deno", "LLM APIs"],
    featured: true,
    status: "shipped",
    // image: "/projects/llmgroupchat.png", // TODO: add screenshot, then uncomment
    links: {
      // TODO: add repo/demo link if public
    },
    caseStudy: {
      problem:
        "A single LLM's stock pick is a coin-flip. I wanted to see whether a *panel* of models — each proposing and scoring ideas — could produce a more reliable signal than any one of them alone.",
      build: [
        "A multi-model consensus pipeline: chats → cycles → iterations → propositions.",
        "MOVDA scoring and a 2-in-a-row winner rule to decide when the panel has actually converged.",
        "Supabase edge functions (Deno 2 runtime) orchestrating the model calls and persistence.",
      ],
    },
  },
  {
    slug: "calorie-tracker",
    title: "AI Calorie-Tracking App",
    tagline:
      "A mobile app that estimates calories and nutrition from a photo of your meal.",
    type: "App",
    year: 2026,
    tech: ["Flutter", "AI Vision", "Mobile"],
    featured: true,
    status: "shipped",
    client: true,
    // image: "/projects/calorie.png", // TODO: add screenshot, then uncomment
    links: {
      // TODO: add store links if published & permitted
    },
    caseStudy: {
      problem:
        "Manual calorie logging is tedious enough that most people quit. The client wanted logging to be as fast as taking a photo.",
      build: [
        "Flutter mobile app (iOS + Android) with a camera-first logging flow.",
        "AI vision integration to identify the meal and estimate calories/macros.",
        "Clean, fast UX designed to remove friction from daily tracking.",
      ],
      results: "Delivered as a client project through Upwork.",
    },
  },
  {
    slug: "polymarket-agent",
    title: "Polymarket Agent",
    tagline:
      "An autonomous AI agent that analyses and trades prediction markets.",
    type: "AI / Agent",
    year: 2026,
    tech: ["TypeScript", "Deno", "Supabase", "LLM APIs"],
    featured: true,
    status: "experiment",
    // image: "/projects/polymarket.png", // TODO: add screenshot, then uncomment
    links: {
      // TODO
    },
    caseStudy: {
      problem:
        "Prediction markets are a rich, real-money testbed for automated reasoning. I wanted an agent that could evaluate markets and act, reusing the consensus infrastructure I'd already built.",
      build: [
        "New agent layer built on the existing consensus tables and edge functions.",
        "Market ingestion, LLM-driven analysis, and decision logic.",
        "Deno-based edge functions for scheduled evaluation.",
      ],
      results:
        "An ongoing experiment in applying automated reasoning to live, real-money prediction markets.",
    },
  },

  // ======================= ARCHIVE ONLY =======================
  {
    slug: "openclaw",
    title: "OpenClaw WhatsApp Bot",
    tagline: "A messaging agent that connects an AI assistant to WhatsApp.",
    type: "Bot",
    year: 2025,
    tech: ["Node.js", "WhatsApp", "LLM APIs"],
    status: "shipped",
  },
  {
    slug: "mivoice",
    title: "MiVoice App",
    tagline: "Mobile app development for a voice-focused client product.",
    type: "App",
    year: 2025,
    tech: ["Flutter", "Mobile"],
    status: "shipped",
    client: true,
  },
  {
    slug: "flutterflow-gemini-voice",
    title: "FlutterFlow + Gemini AI & Voice",
    tagline:
      "Integrated Gemini AI and voice features into a FlutterFlow app for a client.",
    type: "AI / Agent",
    year: 2026,
    tech: ["FlutterFlow", "Gemini", "Voice"],
    status: "shipped",
    client: true,
  },
  {
    slug: "flutter-oauth-multitab",
    title: "Flutter Web OAuth / Multi-Tab Fix",
    tagline:
      "Fixed multi-tab session handling and refresh-token locking in a Flutter web app.",
    type: "Web",
    year: 2026,
    tech: ["Flutter Web", "OAuth", "Auth"],
    status: "shipped",
    client: true,
  },
  {
    slug: "news-app-fix",
    title: "News App Fix",
    tagline: "Diagnosed and fixed issues in a client's Flutter news app.",
    type: "App",
    year: 2025,
    tech: ["Flutter", "Mobile"],
    status: "shipped",
    client: true,
  },
];

// -------------------------- helpers --------------------------
export const featuredProjects = projects.filter((p) => p.featured);
export const projectsWithCaseStudies = projects.filter((p) => p.caseStudy);

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

/** All distinct types present, for the archive filter. */
export const projectTypes = Array.from(
  new Set(projects.map((p) => p.type)),
).sort();
